name: CI
on: [pull_request]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build backend del culo
        run: |
          cd webserver
          cargo build --release
      - uses: purescript-contrib/setup-purescript@main
      - name: Build frontend du cul
        run: |
          cd frontend
          spago build

  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Webserver format
        uses: |
          cd webserver
          cargo fmt --check
